version: '3.8'

services:
  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    ports:
      - '3000:3000'

  agentesolenwhtas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentesolenwhtas_unificado
    ports:
      - "5000:5000"    # API Flask
      - "8501:8501"    # Streamlit webapp
      - "8502:8502"    # Gerenciador de Memória unificado
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    restart: always
    networks:
      default:
        aliases:
          - api  # Permite acessar via http://api:5000

networks:
  default:
    driver: bridge
